In [32]:
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

text1 = 'маслозакачивающий насос не фурычит'
text2 = 'При нажатии кнопки "Пуск дизеля" маслопрокачивающий насос не работает'
text3 = 'не работает маслозакачивающий насос'
text4 = 'маслопрокачивающий насос не работает'

In [6]:
!pip install nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [8]:
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [10]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [15]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def text_similarity(text1, text2):
    # Tokenize and lemmatize the texts
    tokens1 = word_tokenize(text1)
    tokens2 = word_tokenize(text2)
    lemmatizer = WordNetLemmatizer()
    tokens1 = [lemmatizer.lemmatize(token) for token in tokens1]
    tokens2 = [lemmatizer.lemmatize(token) for token in tokens2]

    # Remove stopwords
    stop_words = stopwords.words('english')
    tokens1 = [token for token in tokens1 if token not in stop_words]
    tokens2 = [token for token in tokens2 if token not in stop_words]

    # Create the TF-IDF vectors
    vectorizer = TfidfVectorizer()
    vector1 = vectorizer.fit_transform(tokens1)
    vector2 = vectorizer.transform(tokens2)
    print(vector1)
    print('the next vector')
    print(vector2)
    # Calculate the cosine similarity
    similarity = cosine_similarity(vector1, vector2)

    return similarity

In [16]:
# Convert the texts into TF-IDF vectors
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([text1, text2])

# Calculate the cosine similarity between the vectors
similarity = cosine_similarity(vectors)
print(similarity)

[[1.         0.20608364]
 [0.20608364 1.        ]]


In [17]:
print(text_similarity(text1,text2))

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
the next vector
  (8, 1)	1.0
  (9, 2)	1.0
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 20.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 24.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 49.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 57.8 MB/s eta 0:00:00


In [36]:
import transformers
import numpy as np
# Load the RoBERTa model
def predict_similarity(text1,text2):
    model = transformers.RobertaTokenizerFast.from_pretrained('blinoff/roberta-base-russian-v0', max_len=512)

    # Tokenize and encode the texts

    encoding1 = np.array(model.encode(text1, max_length=512))
    encoding2 = np.array(model.encode(text2, max_length=512))
    print(encoding1)
    print(encoding2)
    encoding1.resize(max(encoding1.size,encoding2.size))
    encoding2.resize(max(encoding1.size,encoding2.size))
    print(encoding1)
    print(encoding2)
    # Calculate the cosine similarity between the embeddings
    similarity = np.dot(encoding1, encoding2) / (np.linalg.norm(encoding1) * np.linalg.norm(encoding2))
    print(similarity)

In [37]:
print(predict_similarity(text1,text2))
print(predict_similarity(text3,text2))
print(predict_similarity(text4,text2))

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


[    0   358  3224  1791   305   401  8966 38756   313  2076   419  1260
     2]
[    0   145   258   321 41756  3804 31913   451   145   258   272   416
 36901   398     6   446  3224   409  4700   401  8966 38756   313  5794
     2]
[    0   358  3224  1791   305   401  8966 38756   313  2076   419  1260
     2     0     0     0     0     0     0     0     0     0     0     0
     0]
[    0   145   258   321 41756  3804 31913   451   145   258   272   416
 36901   398     6   446  3224   409  4700   401  8966 38756   313  5794
     2]
0.105273005250328
None


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


[    0   340  5794   446  3224  1791   305   401  8966 38756     2]
[    0   145   258   321 41756  3804 31913   451   145   258   272   416
 36901   398     6   446  3224   409  4700   401  8966 38756   313  5794
     2]
[    0   340  5794   446  3224  1791   305   401  8966 38756     2     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0]
[    0   145   258   321 41756  3804 31913   451   145   258   272   416
 36901   398     6   446  3224   409  4700   401  8966 38756   313  5794
     2]
0.053499209503901975
None


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


[    0   358  3224   409  4700   401  8966 38756   313  5794     2]
[    0   145   258   321 41756  3804 31913   451   145   258   272   416
 36901   398     6   446  3224   409  4700   401  8966 38756   313  5794
     2]
[    0   358  3224   409  4700   401  8966 38756   313  5794     2     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0]
[    0   145   258   321 41756  3804 31913   451   145   258   272   416
 36901   398     6   446  3224   409  4700   401  8966 38756   313  5794
     2]
0.16311735180564318
None


In [39]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 8.6 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=a1e4d3468eb2b1ad4826ea3381347b260c39d4a5544d4390e3455616ce5d1cc5
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


In [40]:
from sentence_transformers import SentenceTransformer, util
import numpy as np
#%%
model = SentenceTransformer('distiluse-base-multilingual-cased')

In [ ]:
#max_match = 0
#article_id = 10
#id_found = 0
#article_encoded = model.encode(art_res[article_id], convert_to_tensor = True)
#counter = 0
#for i in link_text:
#    sentences = i.split('.')
#    sentences_encoded = model.encode(sentences, convert_to_tensor = True)
#    scores = util.pytorch_cos_sim(article_encoded, sentences_encoded)
#    cur_max = scores[0][np.argpartition(-scores[0], range(1))[0]]
#    if max_match < cur_max:
#        max_match = cur_max
#        id_found = counter
#    counter +=1

In [47]:
import pandas as pd
data = pd.read_excel("/content/parsed_data.xlsx",index_col=0)

In [48]:
data.head()

type  model                                              title  \
0  тепловоз   2М62  При нажатии кнопки "Пуск дизеля" маслопрокачив...   
1  тепловоз  2М62У  При нажатии кнопки "Пуск дизеля" маслопрокачив...   
2  тепловоз   2М62  При нажатии кнопки "Пуск дизеля" маслопрокачив...   
3  тепловоз  2М62У  При нажатии кнопки "Пуск дизеля" маслопрокачив...   
4  тепловоз   2М62  При нажатии кнопки "Пуск дизеля" маслопрокачив...   

              defect                                             reason  \
0  Не включилось РУ6                    Отключился автомат "Управление"   
1  Не включилось РУ6                    Отключился автомат "Управление"   
2  Не включилось РУ6  Реверсивная рукоятка не переведена в положение...   
3  Не включилось РУ6  Реверсивная рукоятка не переведена в положение...   
4  Не включилось РУ6      Контроллер не установлен в нулевое положение.   

                                            solution  
0                     Включить автомат "Управление".  
1                     Включить автомат "Управление".  
2  Установить реверсивную рукоятку в рабочее поло...  
3  Установить реверсивную рукоятку в рабочее поло...  
4         Установить контроллер в нулевое положение.

In [50]:
data.shape[0]

4332

In [95]:
article = 'Не включилось РУ шесть'
article_encoded=model.encode(article,convert_to_tensor= True)

In [76]:
encoded = pd.DataFrame()

In [77]:
third_level_encoded =[]
for i in range(data.shape[0]):
    #print(data.loc[i,'title'])
    try:
        third_level_encoded.append(model.encode(data.loc[i,'title']))
    except:
        third_level_encoded.append(model.encode("NaN"))


In [78]:
encoded['title'] = third_level_encoded

In [79]:
second_level_encoded =[]
for i in range(data.shape[0]):
    #print(data.loc[i,'title'])
    try:
        second_level_encoded.append(model.encode(data.loc[i,'defect']))
    except:
        second_level_encoded.append(model.encode("NaN"))

In [80]:
encoded['defect'] = second_level_encoded

In [81]:
first_level_encoded =[]
for i in range(data.shape[0]):
    #print(data.loc[i,'title'])
    try:
        first_level_encoded.append(model.encode(data.loc[i,'reason']))
    except:
        first_level_encoded.append(model.encode("NaN"))

In [82]:
encoded['reason'] = first_level_encoded

In [83]:
null_level_encoded =[]
for i in range(data.shape[0]):
    #print(data.loc[i,'title'])
    try:
        null_level_encoded.append(model.encode(data.loc[i,'solution']))
    except:
        null_level_encoded.append(model.encode("NaN"))

In [84]:
encoded['solution']=null_level_encoded

In [85]:
encoded.head(5)

title  \
0  [0.004772339, -0.045798708, -0.030039055, -0.0...   
1  [0.004772339, -0.045798708, -0.030039055, -0.0...   
2  [0.004772339, -0.045798708, -0.030039055, -0.0...   
3  [0.004772339, -0.045798708, -0.030039055, -0.0...   
4  [0.004772339, -0.045798708, -0.030039055, -0.0...   

                                              defect  \
0  [0.0022142697, 0.010499295, 0.020204734, 0.034...   
1  [0.0022142697, 0.010499295, 0.020204734, 0.034...   
2  [0.0022142697, 0.010499295, 0.020204734, 0.034...   
3  [0.0022142697, 0.010499295, 0.020204734, 0.034...   
4  [0.0022142697, 0.010499295, 0.020204734, 0.034...   

                                              reason  \
0  [0.077653244, -0.011606734, -0.04002926, 0.009...   
1  [0.077653244, -0.011606734, -0.04002926, 0.009...   
2  [-0.0073062708, -0.027066657, -0.010338017, -0...   
3  [-0.0073062708, -0.027066657, -0.010338017, -0...   
4  [0.06769663, -0.027337171, 0.03246316, -0.0130...   

                                            solution  
0  [0.07519621, -0.026835926, -0.051849097, 0.003...  
1  [0.07519621, -0.026835926, -0.051849097, 0.003...  
2  [0.020207105, -0.019390238, -0.0046668607, -0....  
3  [0.020207105, -0.019390238, -0.0046668607, -0....  
4  [0.07259224, -0.022265056, 0.023697931, 0.0041...

In [86]:
encoded.to_excel("encoded.xlsx")

In [87]:
encoded.to_csv("encoded.csv")

In [88]:
encoded_np=encoded.to_numpy(copy=True)

In [89]:
np.save('encoded.npy', encoded_np)

In [91]:
a= np.load('encoded.npy',allow_pickle=True)

In [ ]:
a

In [96]:
mx= -1000000000000
req=[]
for i in range(len(second_level_encoded)):
    scores = util.pytorch_cos_sim(article_encoded, second_level_encoded[i])
    if scores>mx:
        mx=scores
        req.clear()
        req.append(i)
    elif scores==mx:
        req.append(i)
print(*req)

0 1 2 3 4 5 6 7
